### ISSUE TITLE
sbt-assmbly and deployment without heroku-toolbelt

### ISSUE THREAD

**Issue by hanskoff** [heroku/sbt-heroku#27]
Hi, I like this plugin very much and it helps, but did you try to deploy fat-jar without heroku-toolbelt? I'm building a ci pipeline and would like to deploy that way, right now calling `HEROKU_API_KEY="xxx-xxx-xxxx" sbt deployHeroku` (without stage doesn't work for me) am I doing smth wrong? is documentation misleading and there is no such a feature?

**Comment by jkutner** [comment]
Did you build the fat-jar before running `sbt deployHeroku`? The plugin does not build a fat-jar for you, so you must use [sbt-assembly](https://github.com/sbt/sbt-assembly) to do that. You will also need to configure the fat-jar file to deploy, probably like this:

```scala
herokuFatJar in Compile := Some((assemblyOutputPath in assembly).value)
```

Here is [an example from a test](https://github.com/heroku/sbt-heroku/blob/master/src/sbt-test/fatjar/minimal/build.sbt#L14).

We can't automatically run `stage` for you with a fat-jar because not all plugins do it the same way.

**Comment by hanskoff** [comment]
Yeah, I have fatjar built with sbt-assembly
01.02.2016 3:27 PM "Joe Kutner" <notifications@github.com> napisał(a):

**Comment by jkutner** [comment]
Did you add the `herokuFatJar in Compile` to your `build.sbt`?

What error or behavior are you seeing instead of a successful deploy?

**Comment by hanskoff** [comment]
I'm sorry you are right, I should have include that log

```
[Step 3/3] java.lang.IllegalArgumentException: Could not find app name: No 'heroku' remote found.
[06:08:01][Step 3/3] 	at com.heroku.sdk.deploy.Deployer.<init>(Deployer.java:45)
[06:08:01][Step 3/3] 	at com.heroku.sdk.deploy.BuildsDeployer.<init>(BuildsDeployer.java:24)
[06:08:01][Step 3/3] 	at com.heroku.sdk.deploy.App.<init>(App.java:25)
[06:08:01][Step 3/3] 	at com.heroku.sbt.SbtApp.<init>(SbtApp.scala:13)
[06:08:01][Step 3/3] 	at com.heroku.sbt.HerokuPlugin$autoImport$$anonfun$baseHerokuSettings$2.apply(HerokuPlugin.scala:39)
[06:08:01][Step 3/3] 	at com.heroku.sbt.HerokuPlugin$autoImport$$anonfun$baseHerokuSettings$2.apply(HerokuPlugin.scala:26)
[06:08:01][Step 3/3] 	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[06:08:01][Step 3/3] 	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
[06:08:01][Step 3/3] 	at sbt.std.Transform$$anon$4.work(System.scala:63)
[06:08:01][Step 3/3] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
[06:08:01][Step 3/3] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
[06:08:01][Step 3/3] 	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[06:08:01][Step 3/3] 	at sbt.Execute.work(Execute.scala:235)
[06:08:01][Step 3/3] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
[06:08:01][Step 3/3] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
[06:08:01][Step 3/3] 	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[06:08:01][Step 3/3] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[06:08:01][Step 3/3] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[06:08:01][Step 3/3] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[06:08:01][Step 3/3] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[06:08:01][Step 3/3] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[06:08:01][Step 3/3] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[06:08:01][Step 3/3] 	at java.lang.Thread.run(Thread.java:745)
[06:08:01][Step 3/3] Caused by: java.lang.RuntimeException: No 'heroku' remote found.
[06:08:01][Step 3/3] 	at com.heroku.sdk.deploy.Toolbelt.getAppName(Toolbelt.java:24)
[06:08:01][Step 3/3] 	at com.heroku.sdk.deploy.Deployer.<init>(Deployer.java:43)
[06:08:01][Step 3/3] 	at com.heroku.sdk.deploy.BuildsDeployer.<init>(BuildsDeployer.java:24)
[06:08:01][Step 3/3] 	at com.heroku.sdk.deploy.App.<init>(App.java:25)
[06:08:01][Step 3/3] 	at com.heroku.sbt.SbtApp.<init>(SbtApp.scala:13)
[06:08:01][Step 3/3] 	at com.heroku.sbt.HerokuPlugin$autoImport$$anonfun$baseHerokuSettings$2.apply(HerokuPlugin.scala:39)
[06:08:01][Step 3/3] 	at com.heroku.sbt.HerokuPlugin$autoImport$$anonfun$baseHerokuSettings$2.apply(HerokuPlugin.scala:26)
[06:08:01][Step 3/3] 	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[06:08:01][Step 3/3] 	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
[06:08:01][Step 3/3] 	at sbt.std.Transform$$anon$4.work(System.scala:63)
[06:08:01][Step 3/3] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
[06:08:01][Step 3/3] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
[06:08:01][Step 3/3] 	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[06:08:01][Step 3/3] 	at sbt.Execute.work(Execute.scala:235)
[06:08:01][Step 3/3] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
[06:08:01][Step 3/3] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
[06:08:01][Step 3/3] 	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[06:08:01][Step 3/3] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[06:08:01][Step 3/3] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[06:08:01][Step 3/3] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[06:08:01][Step 3/3] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[06:08:01][Step 3/3] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[06:08:01][Step 3/3] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[06:08:01][Step 3/3] 	at java.lang.Thread.run(Thread.java:745)
```

and yeah, I've got exactly same line in`build.sbt`

```
herokuFatJar in Compile := Some((assemblyOutputPath in assembly).value)
```

**Comment by jkutner** [comment]
Do you have a `heroku` remote in your Git remotes? What is the output when you run `git remote -v`?

If you do not have a Git remote, then you will need to configure the Heroku app name either in your `build.sbt` like this:

```scala
herokuAppName in Compile := "your-heroku-app-name"
```
Or as a command-line option as described with [Deploying to Multiple Environments](https://github.com/heroku/sbt-heroku#deploying-to-multiple-environments).

**Comment by hanskoff** [comment]
Yeah! That was is and it is in the README, excuse me for dump interruption! Your plugin and your job around it are great! Thanks!
